// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TDPC12_ASPNETCore3._1WebAppMVC.Models
{
    public partial class Book
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public bool Read { get; set; }
        public DateTime Date { get; set; }
    }
}